// scripts/generate-seeds.mjs
// Generates the 26 seed skin markdown files from the awesome-codex-skin-projects
// README. previewImage is intentionally OMITTED to exercise the fallback path.
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'src', 'content', 'skins');
mkdirSync(OUT, { recursive: true });

const skins = [
  {
    slug: 'gothic-void-expedition',
    name: 'Gothic Void Expedition',
    author: 'Fei-Away',
    category: 'dark-midnight',
    mood: 'solemn',
    color: '#1A1A2E',
    platform: 'codex-desktop',
    description: 'Gothic Void Expedition is the engine built-in default preset: a solemn cathedral-horizon dark sci-fi look for Codex Desktop.',
    installPrompt: "Codex, switch my workspace to the 'Gothic Void Expedition' preset from Codex Dream Skin — a solemn cathedral-horizon dark sci-fi theme.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/Fei-Away/Codex-Dream-Skin',
    compatibleWith: ['codex-desktop'],
    featured: true,
    installs: 2103,
    likes: 412,
    body: 'Bundled as the default preset of the Codex Dream Skin engine, Gothic Void Expedition leans on near-black surfaces and a faint horizon glow. It is the safest first skin to try because the same engine handles one-click restore.',
  },
  {
    slug: 'mythic-guardian-noir',
    name: 'Mythic Guardian Noir',
    author: 'ChannelerH',
    category: 'dark-midnight',
    mood: 'mysterious',
    color: '#1C1C28',
    platform: 'codex-desktop',
    description: 'Mythic Guardian Noir brings a dark guardian noir palette pulled from the ChannelerH open skin pack and re-shared via BigPizzaV3 themes.',
    installPrompt: "Codex, apply the 'Mythic Guardian Noir' theme from the ChannelerH codex-skin-packs collection — a dark guardian noir palette.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/ChannelerH/codex-skin-packs',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 740,
    likes: 121,
    body: 'Distributed through the ChannelerH skin pack and mirrored in the BigPizzaV3 theme set, Mythic Guardian Noir is a desaturated noir palette suited to late-night focus sessions.',
  },
  {
    slug: 'bearded-tokyo-night',
    name: 'Tokyo Night (CLI)',
    author: 'vufly',
    category: 'dark-midnight',
    mood: 'calm',
    color: '#1A1B26',
    platform: 'codex-cli',
    description: 'Tokyo Night is the dark blue Tokyo Night syntax theme ported to Codex CLI via Bearded Theme Ports.',
    installPrompt: "curl -fsSL https://raw.githubusercontent.com/vufly/bearded-theme-ports/master/scripts/install-codex.sh | sh\n# then in Codex CLI run:\n/theme Tokyo Night",
    installFormat: 'tmtheme',
    sourceUrl: 'https://github.com/vufly/bearded-theme-ports',
    compatibleWith: ['codex-cli'],
    featured: false,
    installs: 980,
    likes: 188,
    body: 'Part of the Bearded Theme Ports collection (50+ variants), this CLI port drops a Tokyo Night .tmTheme into your Codex CLI and is selectable with the /theme command.',
  },
  {
    slug: 'amber-nocturne',
    name: 'amber-nocturne (CLI)',
    author: 'ychampion',
    category: 'dark-midnight',
    mood: 'warm',
    color: '#3B2F1E',
    platform: 'codex-cli',
    description: 'amber-nocturne is a warm-dark branded terminal identity for Codex CLI from the Codex Themes CLI tool.',
    installPrompt: 'codex-theme apply amber-nocturne',
    installFormat: 'tmtheme',
    sourceUrl: 'https://github.com/ychampion/codex-themes',
    compatibleWith: ['codex-cli'],
    featured: false,
    installs: 410,
    likes: 66,
    body: 'Managed by the Go-based Codex Themes CLI, amber-nocturne applies a warm-dark branded prompt and status line through a single validate/apply command.',
  },
  {
    slug: 'clear-glass',
    name: 'Clear Glass',
    author: 'Fei-Away',
    category: 'light-airy',
    mood: 'clean',
    color: '#E8EFF5',
    platform: 'codex-desktop',
    description: 'Clear Glass is a clean, glassy, low-distraction light surface built into the Codex Dream Skin engine.',
    installPrompt: "Codex, apply the 'Clear Glass' light theme — a clean glassy low-distraction surface for my workspace.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/Fei-Away/Codex-Dream-Skin',
    compatibleWith: ['codex-desktop'],
    featured: true,
    installs: 1620,
    likes: 305,
    body: 'A light companion to the engine defaults, Clear Glass uses translucent panels and a high-key palette to keep the interface unobtrusive during daytime work.',
  },
  {
    slug: 'berry-light',
    name: 'Berry (light journal)',
    author: 'duxweb',
    category: 'light-airy',
    mood: 'soft',
    color: '#DCEEF2',
    platform: 'codex-desktop',
    description: 'Berry is a light "handbook" pastel theme for the ReTheme engine.',
    installPrompt: "In ReTheme, open the theme library and apply 'Berry' — a light pastel handbook theme for Codex.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/duxweb/ReTheme',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 530,
    likes: 97,
    body: 'ReTheme is a Tauri-based theme engine for Codex and ChatGPT. Berry is one of its signed, updatable community themes with a soft handbook feel.',
  },
  {
    slug: 'amber-dusk',
    name: 'Amber Dusk',
    author: 'gh283249008',
    category: 'light-airy',
    mood: 'cozy',
    color: '#C8852B',
    platform: 'codex-desktop',
    description: 'Amber Dusk is a warm amber dusk programmatic preset (MIT) from the Codex Cidala Tiger Skin repo.',
    installPrompt: "Codex, switch my workspace to the 'Amber Dusk' engine preset — a warm amber dusk theme.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/gh283249008/Codex-Cidala-Tiger-Skin',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 380,
    likes: 58,
    body: 'Generated programmatically by the Cidala Tiger Skin project, Amber Dusk favors a warm amber wash that reads well in low-light rooms without going fully dark.',
  },
  {
    slug: 'hatsune-miku',
    name: 'Hatsune Miku',
    author: 'Fei-Away',
    category: 'anime-pop',
    mood: 'energetic',
    color: '#39C5BB',
    platform: 'codex-desktop',
    description: 'Hatsune Miku brings blue-green vocaloid energy to your Codex workspace.',
    installPrompt: "Codex, apply the 'Hatsune Miku' skin — blue-green vocaloid energy for my workspace.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/Fei-Away/Codex-Dream-Skin',
    compatibleWith: ['codex-desktop'],
    featured: true,
    installs: 2540,
    likes: 521,
    body: 'One of the most-requested character skins, Hatsune Miku layers a teal vocaloid palette over the Dream Skin engine. Source art belongs to its respective owners.',
  },
  {
    slug: 'dilraba',
    name: 'Dilraba',
    author: 'codex-skin.dev',
    category: 'anime-pop',
    mood: 'playful',
    color: '#E8B4C8',
    platform: 'codex-desktop',
    description: 'Dilraba is a fan-made celebrity concept skin from codex-skin.dev.',
    installPrompt: "On codex-skin.dev, copy the 'Dilraba' install prompt into Codex to apply this fan concept skin.",
    installFormat: 'prompt',
    sourceUrl: 'https://codex-skin.dev/',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 870,
    likes: 143,
    body: 'Built by the codex-skin.dev gallery, Dilraba is a fan-made concept skin applied by pasting the gallery install prompt directly into Codex.',
  },
  {
    slug: 'jackson-yee',
    name: 'Jackson Yee',
    author: 'codex-skin.dev',
    category: 'anime-pop',
    mood: 'serene',
    color: '#6B7A6E',
    platform: 'codex-desktop',
    description: 'Jackson Yee is a fan-made skin with gray-green ink-plant motifs and light panels for all-day use.',
    installPrompt: "On codex-skin.dev, copy the 'Jackson Yee' install prompt into Codex to apply this gray-green skin.",
    installFormat: 'prompt',
    sourceUrl: 'https://codex-skin.dev/zh/skins/jackson-yee',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 690,
    likes: 102,
    body: 'Another codex-skin.dev concept entry, Jackson Yee pairs ink-plant motifs with light panels so the workspace stays readable across a full workday.',
  },
  {
    slug: 'cartethyia',
    name: 'Cartethyia, Wind-Tide Sanctum',
    author: 'hyhang915',
    category: 'anime-pop',
    mood: 'ethereal',
    color: '#5B8FB0',
    platform: 'codex-desktop',
    description: 'Cartethyia, Wind-Tide Sanctum is a game-character skin from the Codex Skin Manager built-in collection.',
    installPrompt: "In Codex Skin Manager, apply the built-in 'Cartethyia, Wind-Tide Sanctum' theme to your workspace.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/hyhang915/Codex-Skin-Manager',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 760,
    likes: 131,
    body: 'Shipped inside the Codex Skin Manager as a built-in theme, Cartethyia uses a wind-tide blue palette drawn from a game character design.',
  },
  {
    slug: 'cyber-neon',
    name: 'Cyber Neon',
    author: 'gh283249008',
    category: 'neon-cyberpunk',
    mood: 'vibrant',
    color: '#FF2A6D',
    platform: 'codex-desktop',
    description: 'Cyber Neon is a neon cyberpunk abstract preset (MIT) from the Codex Cidala Tiger Skin repo.',
    installPrompt: "Codex, switch my workspace to the 'Cyber Neon' engine preset — a neon cyberpunk theme.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/gh283249008/Codex-Cidala-Tiger-Skin',
    compatibleWith: ['codex-desktop'],
    featured: true,
    installs: 1180,
    likes: 234,
    body: 'A high-contrast neon preset from Cidala Tiger Skin, Cyber Neon is for users who want their workspace to read as a cyberpunk terminal at a glance.',
  },
  {
    slug: 'red-white-scifi',
    name: 'Red-White Sci-Fi',
    author: 'Fei-Away',
    category: 'neon-cyberpunk',
    mood: 'futuristic',
    color: '#E63946',
    platform: 'codex-desktop',
    description: 'Red-White Sci-Fi pairs mecha lines with warning red and white futurism.',
    installPrompt: "Codex, apply the 'Red-White Sci-Fi' preset — mecha lines with warning red/white futurism.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/Fei-Away/Codex-Dream-Skin',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 640,
    likes: 110,
    body: 'A Dream Skin engine preset, Red-White Sci-Fi leans on industrial mecha accents and a restrained red/white warning palette.',
  },
  {
    slug: 'blue-enchantress',
    name: 'Blue Enchantress',
    author: 'codexthemes.ai',
    category: 'neon-cyberpunk',
    mood: 'vivid',
    color: '#2D7DF6',
    platform: 'codex-desktop',
    description: 'Blue Enchantress is a blue neon gallery skin from codexthemes.ai.',
    installPrompt: "On codexthemes.ai, copy the 'Blue Enchantress' install prompt into Codex to apply this blue neon skin.",
    installFormat: 'prompt',
    sourceUrl: 'https://codexthemes.ai/',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 510,
    likes: 84,
    body: 'Distributed through codexthemes.ai, Blue Enchantress applies a saturated electric-blue neon scheme via the gallery install prompt.',
  },
  {
    slug: 'vivid-purple',
    name: 'Vivid Purple (CLI)',
    author: 'vufly',
    category: 'neon-cyberpunk',
    mood: 'bold',
    color: '#A020F0',
    platform: 'codex-cli',
    description: 'Vivid Purple is a vivid purple syntax theme ported to Codex CLI via Bearded Theme Ports.',
    installPrompt: "curl -fsSL https://raw.githubusercontent.com/vufly/bearded-theme-ports/master/scripts/install-codex.sh | sh\n# then in Codex CLI run:\n/theme Vivid Purple",
    installFormat: 'tmtheme',
    sourceUrl: 'https://github.com/vufly/bearded-theme-ports',
    compatibleWith: ['codex-cli'],
    featured: false,
    installs: 620,
    likes: 115,
    body: 'A bold purple entry in the Bearded Theme Ports set, Vivid Purple is installed as a CLI .tmTheme and selected with /theme.',
  },
  {
    slug: 'forest-mist',
    name: 'Forest Mist',
    author: 'gh283249008',
    category: 'nature-earthy',
    mood: 'tranquil',
    color: '#4A6B52',
    platform: 'codex-desktop',
    description: 'Forest Mist is a misty forest abstract preset (MIT) from the Codex Cidala Tiger Skin repo.',
    installPrompt: "Codex, switch my workspace to the 'Forest Mist' engine preset — a misty forest theme.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/gh283249008/Codex-Cidala-Tiger-Skin',
    compatibleWith: ['codex-desktop'],
    featured: true,
    installs: 880,
    likes: 167,
    body: 'Forest Mist trades neon for a calm green-gray gradient evoking low-lying woodland fog, generated by the Cidala Tiger Skin project.',
  },
  {
    slug: 'inspiration',
    name: 'Inspiration',
    author: 'Fei-Away',
    category: 'nature-earthy',
    mood: 'glowing',
    color: '#E0A23B',
    platform: 'codex-desktop',
    description: 'Inspiration is a warm amber flow-state glow built into the Codex Dream Skin engine.',
    installPrompt: "Codex, apply the 'Inspiration' preset — a warm amber flow-state glow for deep work.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/Fei-Away/Codex-Dream-Skin',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 940,
    likes: 176,
    body: 'Designed to ease you into long sessions, Inspiration uses a warm amber glow that sits between the engine dark and light defaults.',
  },
  {
    slug: 'kungfu-football',
    name: "Kung Fu Women's Football",
    author: 'codexskins.org',
    category: 'nature-earthy',
    mood: 'spirited',
    color: '#C0392B',
    platform: 'codex-desktop',
    description: "Kung Fu Women's Football pairs cinnabar red with ink-wash — the gallery's first machine-verified installable theme.",
    installPrompt: "Download the .codedrobe-theme file for \"Kung Fu Women's Football\" from codexskins.org and apply it in Codex Desktop.",
    installFormat: 'codedrobe-theme',
    sourceUrl: 'https://www.codexskins.org/',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 430,
    likes: 79,
    body: 'Notable as the first machine-verified installable theme on codexskins.org, it ships as a .codedrobe-theme file that Codex Desktop applies directly.',
  },
  {
    slug: 'qq2007-retro',
    name: 'QQ2007 Retro',
    author: 'codexskins.org',
    category: 'retro-vintage',
    mood: 'nostalgic',
    color: '#5AA9E6',
    platform: 'codex-desktop',
    description: 'QQ2007 Retro dresses Codex like 2007 QQ: a sky-blue window, penguin avatar and a "My Profile" sidebar.',
    installPrompt: "On codexskins.org, download the 'QQ2007 Retro' community theme file and apply it in Codex Desktop.",
    installFormat: 'prompt',
    sourceUrl: 'https://www.codexskins.org/',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 560,
    likes: 92,
    body: 'A playful throwback, QQ2007 Retro recreates the early-2000s instant-messenger window chrome inside the Codex workspace.',
  },
  {
    slug: 'solarized',
    name: 'Solarized (CLI)',
    author: 'vufly',
    category: 'retro-vintage',
    mood: 'classic',
    color: '#FDF6E3',
    platform: 'codex-cli',
    description: 'Solarized is the iconic Solarized palette ported to Codex CLI via Bearded Theme Ports.',
    installPrompt: "curl -fsSL https://raw.githubusercontent.com/vufly/bearded-theme-ports/master/scripts/install-codex.sh | sh\n# then in Codex CLI run:\n/theme Solarized",
    installFormat: 'tmtheme',
    sourceUrl: 'https://github.com/vufly/bearded-theme-ports',
    compatibleWith: ['codex-cli'],
    featured: false,
    installs: 1340,
    likes: 261,
    body: 'The classic Ethan Schoonover palette, ported for Codex CLI. Install the port script once, then select Solarized with /theme.',
  },
  {
    slug: 'sakura-pink-dawn',
    name: 'Sakura Pink Dawn',
    author: 'gh283249008',
    category: 'pastel-soft',
    mood: 'gentle',
    color: '#F7C8D8',
    platform: 'codex-desktop',
    description: 'Sakura Pink Dawn is a soft sakura-pink abstract preset (MIT) from the Codex Cidala Tiger Skin repo.',
    installPrompt: "Codex, switch my workspace to the 'Sakura Pink Dawn' engine preset — a soft sakura-pink theme.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/gh283249008/Codex-Cidala-Tiger-Skin',
    compatibleWith: ['codex-desktop'],
    featured: true,
    installs: 1020,
    likes: 199,
    body: 'A gentle pink preset from Cidala Tiger Skin, Sakura Pink Dawn keeps saturation low so the workspace stays calm rather than candy-bright.',
  },
  {
    slug: 'hashimoto-arata',
    name: 'Hashimoto Arata',
    author: 'Fei-Away',
    category: 'pastel-soft',
    mood: 'soft',
    color: '#E5C0C8',
    platform: 'codex-desktop',
    description: 'Hashimoto Arata is a soft light theme with rose tones — the engine second built-in, machine-tested preset.',
    installPrompt: "Codex, apply the 'Hashimoto Arata' preset — a soft light theme with rose tones.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/Fei-Away/Codex-Dream-Skin',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 770,
    likes: 138,
    body: 'The second machine-tested built-in preset of the Dream Skin engine, Hashimoto Arata is a light, rose-toned theme tuned for daytime readability.',
  },
  {
    slug: 'pink-custom',
    name: 'Pink Custom',
    author: 'Fei-Away',
    category: 'pastel-soft',
    mood: 'dreamy',
    color: '#F2B8C6',
    platform: 'codex-desktop',
    description: 'Pink Custom is a gentle pink gradient built for late-night coding in the Codex Dream Skin engine.',
    installPrompt: "Codex, apply the 'Pink Custom' preset — a gentle pink theme for late-night coding.",
    installFormat: 'prompt',
    sourceUrl: 'https://github.com/Fei-Away/Codex-Dream-Skin',
    compatibleWith: ['codex-desktop'],
    featured: false,
    installs: 650,
    likes: 121,
    body: 'Pink Custom softens the default dark engine with a low-saturation pink wash aimed at comfortable late-night sessions.',
  },
  {
    slug: 'monokai-stone',
    name: 'Monokai Stone (CLI)',
    author: 'vufly',
    category: 'mono-terminal',
    mood: 'crisp',
    color: '#272822',
    platform: 'codex-cli',
    description: 'Monokai Stone is the classic Monokai Stone syntax theme ported to Codex CLI via Bearded Theme Ports.',
    installPrompt: "curl -fsSL https://raw.githubusercontent.com/vufly/bearded-theme-ports/master/scripts/install-codex.sh | sh\n# then in Codex CLI run:\n/theme Monokai Stone",
    installFormat: 'tmtheme',
    sourceUrl: 'https://github.com/vufly/bearded-theme-ports',
    compatibleWith: ['codex-cli'],
    featured: false,
    installs: 1500,
    likes: 290,
    body: 'The familiar Monokai palette, ported for Codex CLI. Install the port script once, then select Monokai Stone with /theme.',
  },
  {
    slug: 'ychampion-tokyo-night',
    name: 'Tokyo Night (ychampion)',
    author: 'ychampion',
    category: 'mono-terminal',
    mood: 'branded',
    color: '#1A1B26',
    platform: 'codex-cli',
    description: 'Tokyo Night (ychampion) is a Tokyo Night terminal identity with a branded status line for Codex CLI.',
    installPrompt: 'codex-theme apply tokyo-night',
    installFormat: 'tmtheme',
    sourceUrl: 'https://github.com/ychampion/codex-themes',
    compatibleWith: ['codex-cli'],
    featured: false,
    installs: 470,
    likes: 81,
    body: 'From the Go-based Codex Themes CLI, this Tokyo Night variant adds a branded status line on top of the standard palette.',
  },
  {
    slug: 'codepilot-skins',
    name: 'Codepilot built-in TUI skins',
    author: 'charzhu',
    category: 'mono-terminal',
    mood: 'terminal',
    color: '#2D2D3A',
    platform: 'codex-cli',
    description: 'Codepilot ships 16 built-in TUI skins (background + surface colors) selectable with /skin.',
    installPrompt: "Install Codepilot with 'npm i -g @charzhu/codepilot', then run '/skin' in the TUI to pick a built-in skin.",
    installFormat: 'manual',
    sourceUrl: 'https://github.com/charzhu/codepilot',
    compatibleWith: ['codex-cli'],
    featured: false,
    installs: 890,
    likes: 152,
    body: 'Codepilot is a Codex CLI distribution with TUI personalization. It bundles 16 background/surface skins you switch with the /skin command, plus built-in terminal pets.',
  },
];

function yamlBlock(key, value) {
  // block scalar preserves newlines and treats # as literal text
  return `${key}: |-\n${value.split('\n').map((l) => '  ' + l).join('\n')}\n`;
}

let count = 0;
for (const s of skins) {
  const lines = [];
  lines.push('---');
  lines.push(`name: ${JSON.stringify(s.name)}`);
  lines.push(`author: ${JSON.stringify(s.author)}`);
  lines.push(`category: ${s.category}`);
  lines.push(`mood: ${JSON.stringify(s.mood)}`);
  lines.push(`color: "${s.color}"`);
  lines.push(`platform: ${s.platform}`);
  lines.push(yamlBlock('description', s.description));
  lines.push(yamlBlock('installPrompt', s.installPrompt));
  lines.push(`installFormat: ${s.installFormat}`);
  // previewImage intentionally omitted
  lines.push(`sourceUrl: ${s.sourceUrl}`);
  lines.push('compatibleWith:');
  for (const p of s.compatibleWith) lines.push(`  - ${p}`);
  lines.push(`featured: ${s.featured ? 'true' : 'false'}`);
  lines.push('updatedAt: 2026-08-10');
  lines.push('stats:');
  lines.push(`  installs: ${s.installs}`);
  lines.push(`  likes: ${s.likes}`);
  lines.push('---');
  lines.push('');
  lines.push(s.body);
  lines.push('');
  const content = lines.join('\n');
  writeFileSync(join(OUT, `${s.slug}.md`), content, 'utf8');
  count++;
}
console.log(`Generated ${count} skin markdown files in ${OUT}`);
